from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
stm32f4xx_it.c
usart.c
""")

# add Ethernet drivers.
if GetDepend('RT_USING_LWIP'):
    src += ['stm32f4xx_eth.c']

# add gpio drivers.
if GetDepend('RT_USING_PIN'):
    src += ['gpio.c']
    
# add sdio drivers.
if GetDepend('RT_USING_SDIO'):
    src += ['sdcard.c']
    
# addw25q16 drivers.
if GetDepend('RT_USING_W25QXX'):
    src += ['w25qxx.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
